### ISSUE TITLE
error when running python clray.py scenes/scene-test.py

### ISSUE THREAD

**Issue by bigdaddyrus** [oseiskar/raytracer#1]
I am running with pyopencl with version 2014.1. Here is the error output truncated.

```
reading OFF with 8 points and 6 faces
constructed 12 triangles
auto-scaling to 40.0%
reading OFF with 8 points and 6 faces
constructed 12 triangles
auto-scaling to 40.0%
reading OFF with 8 points and 6 faces
constructed 12 triangles
auto-scaling to 40.0%
generating normals for 8 vertices
8 vertices
reading OFF with 8 points and 6 faces
constructed 12 triangles
auto-scaling to 40.0%
depth: 0 active nodes: 1 total leaves: 1 active faces: 12
Traceback (most recent call last):
  File "clray.py", line 61, in <module>
    renderer = renderer.Renderer(scene, args)
  File "/Users/xiaruhao/Documents/CS184/raytracer-master/renderer.py", line 49, in __init__
    self.prog = self.acc.build_program(program_code, args.cl_build_options)
  File "/Users/xiaruhao/Documents/CS184/raytracer-master/accelerator.py", line 49, in build_program
    self.prog = cl.Program(self.ctx, prog_code).build(options)
  File "/Users/xiaruhao/anaconda/lib/python2.7/site-packages/pyopencl/__init__.py", line 209, in build
    options=options, source=self._source)
  File "/Users/xiaruhao/anaconda/lib/python2.7/site-packages/pyopencl/__init__.py", line 249, in _build_and_catch_errors
    raise err
pyopencl.RuntimeError: clBuildProgram failed: build program failure - 

Build on <pyopencl.Device 'Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz' on 'Apple' at 0xffffffff>:

<program source>:27:9: warning: no previous prototype for function 'ia_mul'
ia_type ia_mul(ia_type a, ia_type b)
        ^
<program source>:47:9: warning: no previous prototype for function 'ia_pow2'
ia_type ia_pow2(ia_type a)
        ^
<program source>:53:9: warning: no previous prototype for function 'ia_pow3'
ia_type ia_pow3(ia_type a)
        ^
<program source>:58:9: warning: no previous prototype for function 'ia_pow4'
ia_type ia_pow4(ia_type a)
        ^
<program source>:67:8: warning: no previous prototype for function 'apply_linear_transform'
float3 apply_linear_transform(constant const float4 *p_matrix, float3 vector) {
       ^
<program source>:74:8: warning: no previous prototype for function 'apply_transposed_linear_transform'
float3 apply_transposed_linear_transform(constant const float4 *p_matrix, float3 vector) {
       ^
<program source>:81:8: warning: no previous prototype for function 'apply_affine_transform'
float3 apply_affine_transform(constant const float4 *p_mat_and_vec, float3 vector) {
       ^
<program source>:88:8: warning: no previous prototype for function 'quaternion_mult'
float4 quaternion_mult( float4 q1, float4 q2 )
       ^
<program source>:96:8: warning: no previous prototype for function 'quaternion_square'
float4 quaternion_square( float4 q )
       ^
<program source>:256:42: error: Cannot downconvert and widen scalar type 'double' to vector type '__float3'
            r = normalize(gauss_rvec + r * tan(M_PI*0.5*(1.0 - blur)));
                                       ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~
<program source>:350:12: warning: unused variable 'n'
    float3 n = *normal;
           ^
<program source>:352:12: warning: unused variable 'gauss_rvec'
    float3 gauss_rvec = rvecs_cmask_and_light[1].xyz;
           ^
<program source>:351:18: warning: unused variable 'rvec'
    const float3 rvec = rvecs_cmask_and_light[0].xyz;
                 ^
<program source>:355:12: warning: unused variable 'cur_col'
    float3 cur_col;
           ^
<program source>:354:11: warning: unused variable 'cur_prob'
    float cur_prob = 0.0;
          ^
<program source>:362:52: warning: comparison of integers of different signs: '__global uint' (aka '__global unsigned int') and 'const int'
        if ((suppressed >= 0 && *surface_object_id != suppressed) || *surface_object_id == -suppressed)
                                ~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~
<program source>:362:89: warning: comparison of integers of different signs: '__global uint' (aka '__global unsigned int') and 'int'
        if ((suppressed >= 0 && *surface_object_id != suppressed) || *surface_object_id == -suppressed)
                                                                     ~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~
<program source>:469:49: error: Cannot downconvert and widen scalar type 'double' to vector type '__float3'
            r = normalize(gauss_rvec * blur + r * (1.0-blur));
                                              ~ ^ ~~~~~~~~~~
<program source>:621:49: error: Cannot downconvert and widen scalar type 'double' to vector type '__float3'
            r = normalize(gauss_rvec * blur + r * (1.0-blur));
                                              ~ ^ ~~~~~~~~~~
<program source>:747:29: error: Cannot downconvert and widen scalar type 'double' to vector type '__float3'
                            * (*ray_color) * (*pipeline_color) * cmask
                            ^ ~~~~~~~~~~~~
<program source>:767:25: error: Cannot downconvert and widen scalar type 'double' to vector type '__global __float3'
        *pipeline_color *= 2.0 * dot(n,r);
        ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~
<program source>:769:26: error: Cannot downconvert and widen scalar type 'double' to vector type '__global __float3'
    else *pipeline_color *= 0.0;
         ~~~~~~~~~~~~~~~ ^  ~~~
<program source>:1519:57: error: Cannot downconvert and widen scalar type 'double' to vector type 'float __attribute__((ext_vector_type(2)))'
    f = ia_pow2(qr)+ia_pow2(qi)+ia_pow2(qj)+ia_pow2(qk) - 4.0;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~
<program source>:1582:9: warning: unused variable 'qr1'
                float qr1;
        ^

```

**Comment by oseiskar** [comment]
Thank you for reporting! I think I've now fixed the problem: it also occurred on my machine and was fixed by the latest commit. The reason was that OpenCL compiler has become more picky since I last ran it (no longer allows float vectors to be multiplied by scalar doubles or double literals).

**Comment by bigdaddyrus** [comment]
Thanks! Really cool raytracer sir!
